// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220124004310_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Action",
                            Director = "George Lucas",
                            Edited = true,
                            LentTo = "Mitch",
                            Notes = "Solid Movie",
                            Rating = "PG-13",
                            Title = "Star Wars Revenge of the Sith",
                            Year = 2005
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Action",
                            Director = "Richard Marquand",
                            Edited = true,
                            LentTo = "Max",
                            Notes = "A Classic",
                            Rating = "PG",
                            Title = "Star Wars Return of the Jedi",
                            Year = 1983
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "American sports drama",
                            Director = "John G. Avildsen",
                            Edited = false,
                            LentTo = "Glenn",
                            Notes = "The greatest",
                            Rating = "PG",
                            Title = "Rocky",
                            Year = 1976
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
